[build]
builder = "dockerfile"
watchPatterns = ["backend/**/*"]

[deploy]
startCommand = "sh ./start.sh"
healthcheckPath = "/api/health"
healthcheckTimeout = 900
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5
healthcheckInterval = 30

[env]
FLASK_ENV = "production"
PORT = "8000"
PYTHONUNBUFFERED = "1"
GUNICORN_TIMEOUT = "120"
LOG_LEVEL = "DEBUG"
WAIT_FOR_DB_TIMEOUT = "60"