[build]
builder = "dockerfile"
watchPatterns = ["backend/**/*"]

[deploy]
startCommand = "./start.sh"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
healthcheckInterval = 15

[env]
FLASK_ENV = "production"
PORT = "8000"
PYTHONUNBUFFERED = "1"
SECRET_KEY = "0403e15c727b13683035e89b46b2b30afc6184e63b82c1b94ada6dc66b7f4120"
JWT_SECRET_KEY = "467cfbba631f03f2ea40ef4ed6935212516830f3b14e9a0d724755ebd37a83d5"