[build]
builder = "dockerfile"
watchPatterns = ["backend/**/*"]

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[env]
FLASK_ENV = "production"
PORT = "8000" 