[build]
builder = "dockerfile"
watchPatterns = ["backend/**/*"]

[deploy]
startCommand = "./start.sh"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
healthcheckInterval = 15

[env]
FLASK_ENV = "production"
PORT = "8000"
PYTHONUNBUFFERED = "1"
GUNICORN_TIMEOUT = "120"
LOG_LEVEL = "DEBUG"
WAIT_FOR_DB_RETRIES = "60"
WAIT_FOR_DB_INTERVAL = "5"